name = "aspire-math"
main = "src/index.ts"
compatibility_date = "2026-08-30"
workers_dev = false

[[mtls_certificates]]
binding = "LAPTOP_BACKEND_MTLS"
certificate_id = "56964753-03ed-4f3e-89b3-89873425d0ed"
